In [48]:
import json
import numpy as np
from sklearn.model_selection import StratifiedGroupKFold

# load json
annotation = '/opt/ml/dataset/train.json'

with open(annotation) as f:
    data = json.load(f)
    
var = [(ann['image_id'], ann['category_id']) for ann in data['annotations']]

X = np.ones((len(data['annotations']),1))
y = np.array([v[1] for v in var])
groups = np.array([v[0] for v in var])

cv = StratifiedGroupKFold(n_splits=5, shuffle=True, random_state=411)

for train_idx, val_idx in cv.split(X, y, groups):
    print("TRAIN:", groups[train_idx])
    print("      ", y[train_idx])
    print(" TEST:", groups[val_idx])
    print("      ", y[val_idx])

TRAIN: [   0    1    1 ... 4881 4881 4881]
       [0 3 7 ... 7 1 7]
 TEST: [   6   13   13 ... 4882 4882 4882]
       [1 6 7 ... 0 1 1]
TRAIN: [   0    1    1 ... 4882 4882 4882]
       [0 3 7 ... 0 1 1]
 TEST: [   5    5    5 ... 4876 4876 4878]
       [7 0 0 ... 0 2 0]
TRAIN: [   0    3    3 ... 4882 4882 4882]
       [0 2 6 ... 0 1 1]
 TEST: [   1    1    1 ... 4877 4877 4880]
       [3 7 4 ... 7 7 0]
TRAIN: [   1    1    1 ... 4882 4882 4882]
       [3 7 4 ... 0 1 1]
 TEST: [   0    3    3 ... 4881 4881 4881]
       [0 2 6 ... 7 1 7]
TRAIN: [   0    1    1 ... 4882 4882 4882]
       [0 3 7 ... 0 1 1]
 TEST: [   4    4    4 ... 4868 4872 4872]
       [1 1 1 ... 2 4 6]


In [49]:
import copy

for i in range(5):
    globals()["kfold{}".format(i)] = []
    globals()["data_kfold{}".format(i)] = copy.deepcopy(data)

n = 0
for train_idxs, val_idxs in cv.split(X, y, groups):
    for val_idx in val_idxs:
        globals()["kfold{}".format(n)].append(data['annotations'][val_idx])
    
    globals()["data_kfold{}".format(n)]['annotations'] = globals()["kfold{}".format(n)]


In [ ]:
print(globals()['data_kfold0'])